version: '3'
services: #it denotes container
  container_name: 
    image: image_name:latest  
    ports:
      - "port_number:80" 
    volumes:
      - vname:/app-data 
    networks:
      - network_name
networks:
  network_name: 
    driver: bridge 
volumes:
  volume_name: 